import Head from "next/head";
import { Montserrat } from "next/font/google";
import Meta from "@/app/utils/Meta";
import Navbar from "@/app/components/Navbar";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Meta title="Mark Inger" />
      <Head>
        <title>Mark Inger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css"
        />
      </Head>
      <div className="flex flex-col items-center justify-center w-[100%]">
        <div className="container">
          <Navbar />
        </div>

        <div className="container">
          <div className="first-section">
            <div className="first-section-left">
              <div className="first-left-top self-start flex">
                <h1 className="h1-title">
                  Hello, <br />I{"'"}m Mark
                  <div className="mt-[73px] ml-[15px]">
                    <Image
                      src="/emojis/waving_hand.svg"
                      alt="emoji"
                      width={50}
                      height={50}
                    />
                  </div>
                </h1>
              </div>
              <div className="first-left-mid">
                <p className="sub-title">
                  Experienced Web-Developer who’s here to help you promote and
                  improve your business. Together we’ll build the most powerful
                  and modern website
                </p>
              </div>
              <div className="first-left-bottom">
                <button className="action-btn">CONTACT ME</button>
              </div>
            </div>

            <div className="first-section-mid">
              <h2 className="h2-title">
                My Skills &<br />
                Technologies
              </h2>
              <div className="first-mid-techs">
                <i className="devicon-react-original icon" />
                <i className="devicon-nextjs-line icon"/>
                <i className="devicon-typescript-plain icon"></i>
                <i className="devicon-javascript-plain icon"></i>
                <i className="devicon-html5-plain icon"></i>
                <i className="devicon-css3-plain icon"></i>
                <i className="devicon-sass-original icon"></i>
                <i className="devicon-git-plain icon"></i>
              </div>
            </div>

            <div className="first-section-right">
              <Image className="first-image" src={"/memoji.svg"} alt="photo" width={266} height={266} />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
